language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - pypy
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: PLEASE CHANGE ME
install:
    pip install coveralls

# command to run tests, e.g. python setup.py test
script:
    coverage run --source=czml setup.py test

after_success:
    coveralls

notifications:
  email:
    - christian.ledermann@gmail.com
